### ISSUE TITLE
Setup SSL for API

### ISSUE THREAD

**Issue by mattmcmanus** [ummon-server/ummon-server#30]
http://mcavage.github.io/node-restify/#Creating-a-Server

**Comment by mkopinsky** [comment]
An alternative approach to adding this directly to ummon is to proxy ummon-server behind nginx or Apache using those for SSL termination. This is a common pattern for node apps, and simplifies things like certificate management by consolidating SSL termination in one place.

(This is the approach we plan to use for Way to Health.)
